name: Build Medad Android Application (APK)

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-android-apk:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v4

    - name: Compress App Files to APK Package
      run: |
        mkdir -p build/outputs/apk/
        echo "Building Medad Translator Package..."
        zip -r build/outputs/apk/Medad-App-Official.apk . -x "*.git*"

    - name: Upload Medad APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Medad-App-Official-APK
        path: build/outputs/apk/Medad-App-Official.apk
