name: Medad Translation Engine Core

on:
  workflow_dispatch:
    inputs:
      target_file:
        description: 'Path or Name of the Target File/APK'
        required: false
        default: 'input/'

jobs:
  run-translation-engine:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Execute Medad Translation Script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python engine.py ${{ github.event.inputs.target_file }}

    - name: Upload Processed Translation Output
      uses: actions/upload-artifact@v4
      with:
        name: Medad-Translated-Files
        path: output/
